image: python:3.8

services:
  - postgres:latest # Use PostgreSQL as a service

variables:
  POSTGRES_DB: employee_management # Your database name
  POSTGRES_USER: employee_user # Your database user
  POSTGRES_PASSWORD: 123 # Your database password

before_script:
  - apt-get update && apt-get install -y gcc libpq-dev python3-dev
  - pip install -r requirements.txt

stages:
  - test

test_job:
  stage: test
  script:
    - python manage.py migrate # Run migrations
    - python manage.py test # Run tests
